const domainCollection: Iterable<readonly [string, string]> = [
	['miun', 'Mittuniversitetet'],
	['naturvardsverket', 'Naturvårdsverket'],
	['norden', 'Nordiska ministerrådet'],
	['du', 'Högskolan Dalarna'],
	['ri', 'RISE - Research Institutes of Sweden'],
	['esh', 'Ersta Sköndal Bräcke Högskola'],
	['nationalmuseum', 'Nationalmuseum'],
	['ths', 'Enskilda Högskolan Stockholm'],
	['kmh', 'Kungl. Musikhögskolan'],
	['konstfack', 'Konstfack'],
	['swedgeo', 'Statens geotekniska institut '],
	['hkr', 'Högskolan Kristianstad'],
	['rkh', 'Röda Korsets Högskola '],
	['liu', 'Linköpings universitet'],
	['hb', 'Högskolan i Borås'],
	['nrm', 'Naturhistoriska riksmuseet'],
	['lnu', 'Linnéuniversitetet'],
	['fhs', 'Försvarshögskolan'],
	['mau', 'Malmö universitet'],
	['uu', 'Uppsala universitet '],
	['ltu', 'Luleå tekniska universitet'],
	['hv', 'Högskolan Väst'],
	['hh', 'Högskolan i Halmstad'],
	['shh', 'Sophiahemmet Högskola'],
	['kth', 'Kungliga Tekniska Högskolan'],
	['nordiskamuseet', 'Nordiska museet'],
	['hgo', 'Högskolan på Gotland'],
	['fmv', 'Försvarets materielverk'],
	['his', 'Högskolan i Skövde'],
	['test', 'Test'],
	['mdh', 'Mälardalens högskola'],
	['su', 'Stockholms universitet'],
	['ivl', 'IVL Svenska Miljöinstitutet'],
	['hig', 'Högskolan i Gävle'],
	['varldskulturmuseerna', 'Världskulturmuseerna'],
	['gih', 'Gymnastik- och idrottshögskolan'],
	['nai', 'Nordiska Afrikainstitutet'],
	['kkh', 'Kungl. Konsthögskolan'],
	['riksarkivet', 'Riksarkivet'],
	['hj', 'Jönköping University'],
	['ntnu', 'Norges teknisk-naturvitenskapelige universitet'],
	['uniarts', 'Stockholms konstnärliga högskola'],
	['smhi', 'Sveriges meteorologiska och hydrologiska institut '],
	['havochvatten', 'Havs- och vattenmyndigheten'],
	['umu', 'Umeå universitet'],
	['kau', 'Karlstads universitet'],
	['raa', 'Riksantikvarieämbetet'],
	['sh', 'Södertörns högskola'],
	['oru', 'Örebro universitet'],
	['vti', 'Statens väg- och transportforskningsinstitut '],
	['trafikverket', 'Trafikverket'],
	['polar', 'Polarforskningssekretariatet'],
	['hhs', 'Handelshögskolan i Stockholm'],
	['bth', 'Blekinge Tekniska Högskola'],
	['sprakochfolkminnen', 'Institutet för språk och folkminnen'],
];
export default domainCollection;
